name: Tensorflow production images

on:
  push:
    branches: master
    paths:
      - Dockerfile
      - Jupyter/**
      - build.sh
      - images/base/tensorflow_image_tags.txt.prod
      - .github/workflows/prod-tensorflow.yml
  workflow_dispatch:

jobs:
  prod-tensorflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to uodcvip DockerHub organisation
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.UOD_CVIP_DOCKERHUB_USERNAME }}
          password: ${{ secrets.UOD_CVIP_DOCKERHUB_PASSWORD }}

      - name: Login to NVIDIA Container Registry
        uses: docker/login-action@v1
        with:
          registry: nvcr.io
          username: $oauthtoken
          password: ${{ secrets.NVIDIA_CONTAINER_REGISTRY_KEY }}

      - name: Run builds + pushes for *prod* images
        run: |
          chmod +x ./build.sh
          ./build.sh prod tensorflow ${{ secrets.MLM_LICENSE_FILE }}
