name: Production images

on:
  push:
    branches: master
    paths:
      - './Dockerfile'
      - './images/base/**.prod'
      - './build.sh'
      - './Jupyter/**'
      - './.github/workflows/prod.yml'
  workflow_dispatch:

jobs:
  docker-prod-build-n-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to uodcvip DockerHub organisation
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.UOD_CVIP_DOCKERHUB_USERNAME }}
          password: ${{ secrets.UOD_CVIP_DOCKERHUB_PASSWORD }}

      - name: Login to NVIDIA Container Registry
        uses: docker/login-action@v1
        with:
          registry: nvcr.io
          username: \$oauthtoken
          password: ${{ secrets.NVIDIA_CONTAINER_REGISTRY_KEY }}

      - name: Run builds + pushes for *prod* images
        run: |
          cd ./ServerImageBuilder
          ./build.sh all prod ${{ secrets.MLM_LICENSE_FILE }}
